<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Backend\SPM\SubLayanan;

class SubLayananSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $subLayananDataVersiOne = [
            [
                'layanan_id' => 1,
                'kode' => '1.A.1',
                'uraian' => 'Pelayanan Kesehatan Ibu Hamil',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 1,
                'kode' => '2.A.1',
                'uraian' => 'Pelayanan Kesehatan Ibu Bersalin',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 1,
                'kode' => '3.A.1',
                'uraian' => 'Pelayanan Kesehatan Bayi Baru Lahir',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 1,
                'kode' => '4.A.1',
                'uraian' => 'Pelayanan Kesehatan Balita',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 1,
                'kode' => '5.A.1',
                'uraian' => 'Pelayanan Kesehatan Pada Usia Pendidikan Dasar',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 1,
                'kode' => '6.A.1',
                'uraian' => 'Pelayanan Kesehatan Pada Usia Produktif',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 1,
                'kode' => '7.A.1',
                'uraian' => 'Pelayanan Kesehatan Pada Usia Lanjut',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 1,
                'kode' => '8.A.1',
                'uraian' => 'Pelayanan Kesehatan Penderita Hipertensi',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 1,
                'kode' => '9.A.1',
                'uraian' => 'Pelayanan Kesehatan Penderita Diabetes Melitus',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 1,
                'kode' => '10.A.1',
                'uraian' => 'Pelayanan Kesehatan Orang Dengan Gangguan Jiwa (ODGJ) Berat',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 1,
                'kode' => '11.A.1',
                'uraian' => 'Pelayanan Kesehatan Orang Terduga Tuberkulosis',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 1,
                'kode' => '12.A.1',
                'uraian' => 'Pelayanan Kesehatan Orang Dengan Risiko Terinfeksi Virus Yang Melemahkan Daya Tahan Tubuh Manusia (Human Immunodeficiency Virus)',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 2,
                'kode' => '1.B.1',
                'uraian' => 'Vaksin Tetanus Difteri (Td)',
                'satuan' => 'Ampul',
            ],
            [
                'layanan_id' => 2,
                'kode' => '1.B.2',
                'uraian' => 'Tablet tambah darah',
                'satuan' => 'Tablet',
            ],
            [
                'layanan_id' => 2,
                'kode' => '1.B.3',
                'uraian' => 'Alat deteksi resiko Ibu Hamil : Test Kehamilan',
                'satuan' => 'Paket',
            ],
            [
                'layanan_id' => 2,
                'kode' => '1.B.4',
                'uraian' => 'Alat deteksi resiko Ibu Hamil : Pemeriksaan HB',
                'satuan' => 'Paket',
            ],
            [
                'layanan_id' => 2,
                'kode' => '1.B.5',
                'uraian' => 'Alat deteksi resiko Ibu Hamil : Pemeriksaan Golongan Darah',
                'satuan' => 'Paket',
            ],
            [
                'layanan_id' => 2,
                'kode' => '1.B.6',
                'uraian' => 'Alat deteksi resiko Ibu Hamil : Pemeriksaan Glukoprotein Urin',
                'satuan' => 'Paket',
            ],
            [
                'layanan_id' => 2,
                'kode' => '1.B.7',
                'uraian' => 'Kartu ibu/rekam medis ibu',
                'satuan' => 'Paket',
            ],
            [
                'layanan_id' => 2,
                'kode' => '1.B.8',
                'uraian' => 'Buku Kesehatan Ibu dan Anak (KIA)',
                'satuan' => 'Buku',
            ],
            [
                'layanan_id' => 2,
                'kode' => '1.B.9',
                'uraian' => 'Tenaga kesehatan : Dokter/dokter spesialis kebidanan',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 2,
                'kode' => '1.B.10',
                'uraian' => 'Tenaga kesehatan : Bidan',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 2,
                'kode' => '1.B.11',
                'uraian' => 'Tenaga kesehatan : Perawat',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 2,
                'kode' => '1.B.12',
                'uraian' => 'Kunjungan 4 kali ibu hamil selama periode kehamilan (K4) (Satu kali pada trimester pertama, Satu kali pada trimester kedua, Dua kali pada trimester ketiga)',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 2,
                'kode' => '2.B.1',
                'uraian' => 'Formulir Partograf',
                'satuan' => 'Formulir',
            ],
            [
                'layanan_id' => 2,
                'kode' => '2.B.2',
                'uraian' => 'Kartu ibu (rekam medis)',
                'satuan' => 'Paket',
            ],
            [
                'layanan_id' => 2,
                'kode' => '2.B.3',
                'uraian' => 'Buku Kesehatan Ibu dan Anak (KIA)',
                'satuan' => 'Buku',
            ],
            [
                'layanan_id' => 2,
                'kode' => '2.B.4',
                'uraian' => 'Tenaga kesehatan: Dokter/dokter spesialis Kebidanan dan Kandungan',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 2,
                'kode' => '2.B.5',
                'uraian' => 'Tenaga kesehatan: Bidan',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 2,
                'kode' => '2.B.6',
                'uraian' => 'Tenaga kesehatan: Perawat',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 2,
                'kode' => '3.B.1',
                'uraian' => 'Vaksin Hepatitis B0',
                'satuan' => 'Vaksin',
            ],
            [
                'layanan_id' => 2,
                'kode' => '3.B.2',
                'uraian' => 'Vitamin K1 injeksi',
                'satuan' => 'Ampul',
            ],
            [
                'layanan_id' => 2,
                'kode' => '3.B.3',
                'uraian' => 'Salep/tetes mata antibiotik',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 2,
                'kode' => '3.B.4',
                'uraian' => 'Formulir bayi baru lahir',
                'satuan' => 'Formulir',
            ],
            [
                'layanan_id' => 2,
                'kode' => '3.B.5',
                'uraian' => 'Formulir Manajemen Terpadu Bayi Muda (MTBM)',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 2,
                'kode' => '3.B.6',
                'uraian' => 'Buku Kesehatan Ibu dan Anak (KIA)',
                'satuan' => 'Buku',
            ],
            [
                'layanan_id' => 2,
                'kode' => '3.B.7',
                'uraian' => 'Tenaga kesehatan: Dokter/dokter spesialis Anak',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 2,
                'kode' => '3.B.8',
                'uraian' => 'Tenaga kesehatan: Bidan',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 2,
                'kode' => '3.B.9',
                'uraian' => 'Tenaga kesehatan: Perawat',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 2,
                'kode' => '4.B.1',
                'uraian' => 'Kuisioner Pra Skrining Perkembangan (KPSP) atau instrumen standar lain yang berlaku',
                'satuan' => 'Dokumen',
            ],
            [
                'layanan_id' => 2,
                'kode' => '4.B.2',
                'uraian' => 'Formulir Deteksi Dini Tumbuh Kembang Anak (DDTK)',
                'satuan' => 'Formulir',
            ],
            [
                'layanan_id' => 2,
                'kode' => '4.B.3',
                'uraian' => 'Buku Kartu Ibu dan Anak (KIA)',
                'satuan' => 'Buku',
            ],
            [
                'layanan_id' => 2,
                'kode' => '4.B.4',
                'uraian' => 'Vitamin A Biru',
                'satuan' => 'Kapsul',
            ],
            [
                'layanan_id' => 2,
                'kode' => '4.B.5',
                'uraian' => 'Vitamin A Merah',
                'satuan' => 'Kapsul',
            ],
            [
                'layanan_id' => 2,
                'kode' => '4.B.6',
                'uraian' => 'Vaksin imunisasi dasar: HBO',
                'satuan' => 'Vaksin',
            ],
            [
                'layanan_id' => 2,
                'kode' => '4.B.7',
                'uraian' => 'Vaksin imunisasi dasar: BCG',
                'satuan' => 'Vaksin',
            ],
            [
                'layanan_id' => 2,
                'kode' => '4.B.8',
                'uraian' => 'Vaksin imunisasi dasar: Polio',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 2,
                'kode' => '4.B.9',
                'uraian' => 'Vaksin imunisasi dasar: IPV',
                'satuan' => 'Vaksin',
            ],
            [
                'layanan_id' => 2,
                'kode' => '4.B.10',
                'uraian' => 'Vaksin imunisasi dasar: DPT -HB -Hib',
                'satuan' => 'Vaksin',
            ],
            [
                'layanan_id' => 2,
                'kode' => '4.B.11',
                'uraian' => 'Vaksin imunisasi dasar: Campak',
                'satuan' => 'Vaksin',
            ],
            [
                'layanan_id' => 2,
                'kode' => '4.B.12',
                'uraian' => 'Vaksin imunisasi dasar: Rubella',
                'satuan' => 'Vaksin',
            ],
            [
                'layanan_id' => 2,
                'kode' => '4.B.13',
                'uraian' => 'Vaksin imunisasi lanjutan: DPT -HB -Hib',
                'satuan' => 'Vaksin',
            ],
            [
                'layanan_id' => 2,
                'kode' => '4.B.14',
                'uraian' => 'Vaksin imunisasi lanjutan: Campak',
                'satuan' => 'Vaksin',
            ],
            [
                'layanan_id' => 2,
                'kode' => '4.B.15',
                'uraian' => 'Vaksin imunisasi lanjutan: Rubella',
                'satuan' => 'Vaksin',
            ],
            [
                'layanan_id' => 2,
                'kode' => '4.B.16',
                'uraian' => 'Jarum suntik dan Bahan Habis Pakai (BHP)',
                'satuan' => 'Unit',
            ],
            [
                'layanan_id' => 2,
                'kode' => '4.B.17',
                'uraian' => 'Peralatan Anafilaktik',
                'satuan' => 'Paket',
            ],
            [
                'layanan_id' => 2,
                'kode' => '4.B.18',
                'uraian' => 'Tenaga kesehatan : Dokter',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 2,
                'kode' => '4.B.19',
                'uraian' => 'Tenaga kesehatan : Bidan',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 2,
                'kode' => '4.B.20',
                'uraian' => 'Tenaga kesehatan : Perawat',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 2,
                'kode' => '4.B.21',
                'uraian' => 'Tenaga kesehatan : Ahli Gizi',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 2,
                'kode' => '4.B.22',
                'uraian' => 'Tenaga kesehatan : Kader Kesehatan',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 2,
                'kode' => '4.B.23',
                'uraian' => 'Tenaga Non kesehatan : Guru PAUD',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 2,
                'kode' => '5.B.1',
                'uraian' => 'Buku raport kesehatanku',
                'satuan' => 'Buku',
            ],
            [
                'layanan_id' => 2,
                'kode' => '5.B.2',
                'uraian' => 'Buku pemantauan kesehatan',
                'satuan' => 'Buku',
            ],
            [
                'layanan_id' => 2,
                'kode' => '5.B.3',
                'uraian' => 'Kuesioner skrining kesehatan',
                'satuan' => 'Dokumen',
            ],
            [
                'layanan_id' => 2,
                'kode' => '5.B.4',
                'uraian' => 'Formulir rekapitulasi hasil pelayanan kesehatan usia sekolah dan remaja di dalam sekolah',
                'satuan' => 'Dokumen',
            ],
            [
                'layanan_id' => 2,
                'kode' => '5.B.5',
                'uraian' => 'Formulir rekapitulasi hasil pelayanan kesehatan usia sekolah dan remaja di luar sekolah',
                'satuan' => 'Formulir',
            ],
            [
                'layanan_id' => 2,
                'kode' => '5.B.6',
                'uraian' => 'Tenaga kesehatan: Dokter/Dokter gigi',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 2,
                'kode' => '5.B.7',
                'uraian' => 'Tenaga kesehatan: Bidan',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 2,
                'kode' => '5.B.8',
                'uraian' => 'Tenaga kesehatan: Perawat',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 2,
                'kode' => '5.B.9',
                'uraian' => 'Tenaga kesehatan: Ahli Gizi',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 2,
                'kode' => '5.B.10',
                'uraian' => 'Tenaga Kesehatan: Masyarakat',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 2,
                'kode' => '5.B.11',
                'uraian' => 'Tenaga kesehatan: Kader Kesehatan',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 2,
                'kode' => '5.B.12',
                'uraian' => 'Tenaga Non kesehatan: Guru',
                'satuan' => 'Orang',
            ],
            // Data untuk layanan_id 6
            [
                'layanan_id' => 2,
                'kode' => '6.B.1',
                'uraian' => 'Pedoman dan media Komunikasi, Informasi, Edukasi (KIE)',
                'satuan' => 'Pedoman',
            ],
            [
                'layanan_id' => 2,
                'kode' => '6.B.2',
                'uraian' => 'Alat ukur berat badan',
                'satuan' => 'Unit',
            ],
            [
                'layanan_id' => 2,
                'kode' => '6.B.3',
                'uraian' => 'Alat: Alat ukur tinggi badan',
                'satuan' => 'Unit',
            ],
            [
                'layanan_id' => 2,
                'kode' => '6.B.4',
                'uraian' => 'Alat: Alat ukur lingkar perut',
                'satuan' => 'Unit',
            ],
            [
                'layanan_id' => 2,
                'kode' => '6.B.5',
                'uraian' => 'Alat: Tensimeter',
                'satuan' => 'Unit',
            ],
            [
                'layanan_id' => 2,
                'kode' => '6.B.6',
                'uraian' => 'Alat: Glukometer',
                'satuan' => 'Unit',
            ],
            [
                'layanan_id' => 2,
                'kode' => '6.B.7',
                'uraian' => 'Alat: Tes strip gula darah',
                'satuan' => 'Unit',
            ],
            [
                'layanan_id' => 2,
                'kode' => '6.B.8',
                'uraian' => 'Alat: Lancet',
                'satuan' => 'Unit',
            ],
            [
                'layanan_id' => 2,
                'kode' => '6.B.9',
                'uraian' => 'Alat: Kapas alkohol',
                'satuan' => 'Unit',
            ],
            [
                'layanan_id' => 2,
                'kode' => '6.B.10',
                'uraian' => 'Alat: KIT IVA Tes',
                'satuan' => 'Unit',
            ],
            [
                'layanan_id' => 2,
                'kode' => '6.B.11',
                'uraian' => 'Formulir pencatatan dan pelaporan aplikasi Sistem Informasi Penyakit Tidak Menular (SIPTM)',
                'satuan' => 'Dokumen',
            ],
            [
                'layanan_id' => 2,
                'kode' => '6.B.12',
                'uraian' => 'Tenaga kesehatan: Dokter',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 2,
                'kode' => '6.B.13',
                'uraian' => 'Tenaga kesehatan: Bidan',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 2,
                'kode' => '6.B.14',
                'uraian' => 'Tenaga kesehatan: Perawat',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 2,
                'kode' => '6.B.15',
                'uraian' => 'Tenaga kesehatan: Ahli Gizi',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 2,
                'kode' => '6.B.16',
                'uraian' => 'Tenaga Kesehatan Masyarakat',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 2,
                'kode' => '6.B.17',
                'uraian' => 'Tenaga non kesehatan Terlatih/Mempunyai Kualifikasi tertentu',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 2,
                'kode' => '7.B.1',
                'uraian' => 'Strip uji pemeriksaan gula darah, kolesterol',
                'satuan' => 'Paket',
            ],
            [
                'layanan_id' => 2,
                'kode' => '7.B.2',
                'uraian' => 'Instrumen Geriatric Depression Scale (GDS), Intrumen Abbreviated Mental Test (AMT) dan Instrumen Activity Daily Living (ADL) dalam Paket Pengkajian Paripurna Pasien Geriatri (P3G)',
                'satuan' => 'Paket',
            ],
            [
                'layanan_id' => 2,
                'kode' => '7.B.3',
                'uraian' => 'Buku kesehatan lansia',
                'satuan' => 'Buku',
            ],
            [
                'layanan_id' => 2,
                'kode' => '7.B.4',
                'uraian' => 'Tenaga kesehatan: Dokter',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 2,
                'kode' => '7.B.5',
                'uraian' => 'Tenaga kesehatan: Bidan',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 2,
                'kode' => '7.B.6',
                'uraian' => 'Tenaga kesehatan: Perawat',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 2,
                'kode' => '7.B.7',
                'uraian' => 'Tenaga kesehatan: Ahli Gizi',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 2,
                'kode' => '7.B.8',
                'uraian' => 'Tenaga K esehatan Masyarakat',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 2,
                'kode' => '7.B.9',
                'uraian' => 'Tenaga non kesehatan Terlatih/Mempunyai Kualifikasi tertentu',
                'satuan' => 'Orang',
            ],
            // Data untuk layanan_id 8
            [
                'layanan_id' => 2,
                'kode' => '8.B.1',
                'uraian' => 'Pedoman pengendalian Hipertensi dan media Komunikasi, Informasi, Edukasi (KIE)',
                'satuan' => 'Pedoman',
            ],
            [
                'layanan_id' => 2,
                'kode' => '8.B.2',
                'uraian' => 'Tensimeter',
                'satuan' => 'Unit',
            ],
            [
                'layanan_id' => 2,
                'kode' => '8.B.3',
                'uraian' => 'Formulir pencatatan dan pelaporan aplikasi Sistem Informasi Penyakit Tidak Menular (SIPTM)',
                'satuan' => 'Dokumen',
            ],
            [
                'layanan_id' => 2,
                'kode' => '8.B.4',
                'uraian' => 'Tenaga kesehatan: Dokter',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 2,
                'kode' => '8.B.5',
                'uraian' => 'Tenaga kesehatan: Bidan',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 2,
                'kode' => '8.B.6',
                'uraian' => 'Tenaga kesehatan: Perawat',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 2,
                'kode' => '8.B.7',
                'uraian' => 'Tenaga Kesehatan Masyarakat',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 2,
                'kode' => '8.B.8',
                'uraian' => 'Obat Hipertensi',
                'satuan' => 'Paket',
            ],
            // Data untuk layanan_id 9
            [
                'layanan_id' => 2,
                'kode' => '9.B.1',
                'uraian' => 'Alat: Glukometer',
                'satuan' => 'Unit',
            ],
            [
                'layanan_id' => 2,
                'kode' => '9.B.2',
                'uraian' => 'Alat: Strip Tes Gula Darah',
                'satuan' => 'Unit',
            ],
            [
                'layanan_id' => 2,
                'kode' => '9.B.3',
                'uraian' => 'Alat: Kapas Alkohol',
                'satuan' => 'Unit',
            ],
            [
                'layanan_id' => 2,
                'kode' => '9.B.4',
                'uraian' => 'Alat: Lancet',
                'satuan' => 'Unit',
            ],
            [
                'layanan_id' => 2,
                'kode' => '9.B.5',
                'uraian' => 'Formulir pencatatan dan pelaporan aplikasi Sistem Informasi Penyakit Tidak Menular (SIPTM)',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 2,
                'kode' => '9.B.6',
                'uraian' => 'Pedoman dan media Komunikasi, Informasi, Edukasi (KIE)',
                'satuan' => 'Pedoman',
            ],
            [
                'layanan_id' => 2,
                'kode' => '9.B.7',
                'uraian' => 'Tenaga kesehatan: Dokter',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 2,
                'kode' => '9.B.8',
                'uraian' => 'Tenaga kesehatan: Bidan',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 2,
                'kode' => '9.B.9',
                'uraian' => 'Tenaga kesehatan: Perawat',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 2,
                'kode' => ' 9.B.10',
                'uraian' => 'Tenaga kesehatan: Ahli Gizi',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 2,
                'kode' => '9.B.11',
                'uraian' => 'Tenaga Kesehatan Masyarakat',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 2,
                'kode' => '9.B.12',
                'uraian' => 'Obat Diabetes Melitus',
                'satuan' => 'Paket',
            ],
            [
                'layanan_id' => 2,
                'kode' => '10.B.1',
                'uraian' => 'Buku Pedoman Diagnosis Penggolongan Gangguan Jiwa (PPDGJ III) atau Buku Pedoman Diagnosis Penggolongan Gangguan Jiwa terbaru (bila sudah tersedia)',
                'satuan' => 'Buku',
            ],
            [
                'layanan_id' => 2,
                'kode' => '10.B.2',
                'uraian' => 'Kit berisi 2 Alat Fiksasi',
                'satuan' => 'Paket',
            ],
            [
                'layanan_id' => 2,
                'kode' => '10.B.3',
                'uraian' => 'Penyediaan formulir pencatatan dan pelaporan',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 2,
                'kode' => '10.B.4',
                'uraian' => 'Media Komunikasi, Informasi, Edukasi (KIE)',
                'satuan' => 'Media',
            ],
            [
                'layanan_id' => 2,
                'kode' => '10.B.5',
                'uraian' => 'Tenaga kesehatan: Dokter',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 2,
                'kode' => '10.B.6',
                'uraian' => 'Tenaga kesehatan: Perawat Terlatih Jiwa',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 2,
                'kode' => '10.B.7',
                'uraian' => 'Tenaga kesehatan: Tenaga Kesehatan Lainnya',
                'satuan' => 'Orang',
            ],
            // Data untuk layanan_id 11
            [
                'layanan_id' => 2,
                'kode' => '11.B.1',
                'uraian' => 'Media KIE (Leaflet, Lembar Balik, Poster, Banner)',
                'satuan' => 'Media',
            ],
            [
                'layanan_id' => 2,
                'kode' => '11.B.2',
                'uraian' => 'Reagen Zn TB',
                'satuan' => 'Paket',
            ],
            [
                'layanan_id' => 2,
                'kode' => '11.B.3',
                'uraian' => 'Masker jenis rumah tangga dan Masker N95',
                'satuan' => 'Paket',
            ],
            [
                'layanan_id' => 2,
                'kode' => '11.B.4',
                'uraian' => 'Pot dahak, Kaca slide, Bahan Habis Pakai (Oil Emersi, Ether Alkohol Lampu Spirtus/Bunsen, Ose/Lidi), Rak pengering',
                'satuan' => 'Paket',
            ],
            [
                'layanan_id' => 2,
                'kode' => '11.B.5',
                'uraian' => 'Catridge tes cepat molekuler',
                'satuan' => 'Paket',
            ],
            [
                'layanan_id' => 2,
                'kode' => '11.B.6',
                'uraian' => 'Formulir pencatatan dan pelaporan',
                'satuan' => 'Dokumen',
            ],
            [
                'layanan_id' => 2,
                'kode' => '11.B.7',
                'uraian' => 'Pedoman/Standar Operasional Prosedur (SOP)',
                'satuan' => 'Dokumen',
            ],
            [
                'layanan_id' => 2,
                'kode' => '11.B.8',
                'uraian' => 'Dokter/ dokter spesialis penyakit dalam/ dokter spesialis paru',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 2,
                'kode' => '11.B.9',
                'uraian' => 'Tenaga kesehatan: Perawat',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 2,
                'kode' => '11.B.10',
                'uraian' => 'Tenaga kesehatan: Analis Teknik Laboratorium Medik (ATLM)',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 2,
                'kode' => '11.B.11',
                'uraian' => 'Tenaga kesehatan: Penata Rontgen',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 2,
                'kode' => '11.B.12',
                'uraian' => 'Tenaga kesehatan masyarakat',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 2,
                'kode' => '11.B.13',
                'uraian' => 'Tenaga non kesehatan Terlatih/Mempunyai Kualifikasi tertentu',
                'satuan' => 'Orang',
            ],
            // Data untuk layanan_id 12
            [
                'layanan_id' => 2,
                'kode' => '12.B.1',
                'uraian' => 'Media KIE (Lembar Balik, Leaflet, Poster, Banner)',
                'satuan' => 'Media',
            ],
            [
                'layanan_id' => 2,
                'kode' => '12.B.2',
                'uraian' => 'Tes cepat HIV (RDT) pertama',
                'satuan' => 'Paket',
            ],
            [
                'layanan_id' => 2,
                'kode' => '12.B.3',
                'uraian' => 'Bahan Medis Habis Pakai, Handschoen, Alkohol Swab, Plester, Lancet/Jarum Steril, Jarum Spuit yang sesuai/Vacutainer dan Jarum Sesuai',
                'satuan' => 'Paket',
            ],
            [
                'layanan_id' => 2,
                'kode' => '12.B.4',
                'uraian' => 'Alat tulis, Rekam medis yang berisi nomor rekam medis, Nomor fasilitas pelayanan kesehatan pelaksana, Nomor KTP/NIK',
                'satuan' => 'Paket',
            ],
            [
                'layanan_id' => 2,
                'kode' => '12.B.5',
                'uraian' => 'Tenaga kesehatan: Dokter/dokter spesialis penyakit dalam/dokter spesialis kulit dan kelamin',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 2,
                'kode' => '12.B.6',
                'uraian' => 'Tenaga kesehatan: Perawat',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 2,
                'kode' => '12.B.7',
                'uraian' => 'Tenaga kesehatan: Bidan',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 2,
                'kode' => '12.B.8',
                'uraian' => 'Tenaga kesehatan: Ahli Teknologi Laboratorium Medis (ATLM)',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 2,
                'kode' => '12.B.9',
                'uraian' => 'Tenaga kesehatan masyarakat',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 2,
                'kode' => '12.B.10',
                'uraian' => 'Tenaga non kesehatan terlatih atau mempunyai kualifikasi tertentu',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 3,
                'kode' => '1.C.1',
                'uraian' => 'Pelayanan Kesehatan Ibu Hamil',
                'satuan' => 'Rupiah',
            ],
            [
                'layanan_id' => 3,
                'kode' => '1.C.2',
                'uraian' => 'Pelayanan Kesehatan Ibu Bersalin',
                'satuan' => 'Rupiah',
            ],
            [
                'layanan_id' => 3,
                'kode' => '1.C.3',
                'uraian' => 'Pelayanan Kesehatan Bayi Baru Lahir',
                'satuan' => 'Rupiah',
            ],
            [
                'layanan_id' => 3,
                'kode' => '1.C.4',
                'uraian' => 'Pelayanan Kesehatan Balita',
                'satuan' => 'Rupiah',
            ],
            [
                'layanan_id' => 3,
                'kode' => '1.C.5',
                'uraian' => 'Pelayanan Kesehatan Pada Usia Pendidikan Dasar',
                'satuan' => 'Rupiah',
            ],
            [
                'layanan_id' => 3,
                'kode' => '1.C.6',
                'uraian' => 'Pelayanan Kesehatan Pada Usia Produktif',
                'satuan' => 'Rupiah',
            ],
            [
                'layanan_id' => 3,
                'kode' => '1.C.7',
                'uraian' => 'Pelayanan Kesehatan Pada Usia Lanjut',
                'satuan' => 'Rupiah',
            ],
            [
                'layanan_id' => 3,
                'kode' => '1.C.8',
                'uraian' => 'Pelayanan Kesehatan Penderita Hipertensi',
                'satuan' => 'Rupiah',
            ],
            [
                'layanan_id' => 3,
                'kode' => '1.C.9',
                'uraian' => 'Pelayanan Kesehatan Penderita Diabetes Melitus',
                'satuan' => 'Rupiah',
            ],
            [
                'layanan_id' => 3,
                'kode' => '1.C.10',
                'uraian' => 'Pelayanan Kesehatan Orang Dengan Gangguan Jiwa (ODGJ) Berat',
                'satuan' => 'Rupiah',
            ],
            [
                'layanan_id' => 3,
                'kode' => '1.C.11',
                'uraian' => 'Pelayanan Kesehatan Orang Terduga Tuberkulosis',
                'satuan' => 'Rupiah',
            ],
            [
                'layanan_id' => 3,
                'kode' => '1.C.12',
                'uraian' => 'Pelayanan Kesehatan Orang Dengan Risiko Terinfeksi Virus Yang Melemahkan Daya Tahan Tubuh Manusia (Human Immunodeficiency Virus)',
                'satuan' => 'Rupiah',
            ],
        ];

        $subLayananDataVersiTwo = [
            [
                'layanan_id' => 1,
                'kode' => '1.A.1',
                'uraian' => 'Pelayanan Kesehatan Ibu Hamil',
                'satuan' => 'Orang',
                'versi' => 2,
            ],
            [
                'layanan_id' => 1,
                'kode' => '2.A.1',
                'uraian' => 'Pelayanan Kesehatan Ibu Bersalin',
                'satuan' => 'Orang',
                'versi' => 2,
            ],
            [
                'layanan_id' => 1,
                'kode' => '3.A.1',
                'uraian' => 'Pelayanan Kesehatan Bayi Baru Lahir',
                'satuan' => 'Orang',
                'versi' => 2,
            ],
            [
                'layanan_id' => 1,
                'kode' => '4.A.1',
                'uraian' => 'Pelayanan Kesehatan Balita',
                'satuan' => 'Orang',
                'versi' => 2,
            ],
            [
                'layanan_id' => 1,
                'kode' => '5.A.1',
                'uraian' => 'Pelayanan Kesehatan Pada Usia Pendidikan Dasar',
                'satuan' => 'Orang',
                'versi' => 2,
            ],
            [
                'layanan_id' => 1,
                'kode' => '6.A.1',
                'uraian' => 'Pelayanan Kesehatan Pada Usia Produktif',
                'satuan' => 'Orang',
                'versi' => 2,
            ],
            [
                'layanan_id' => 1,
                'kode' => '7.A.1',
                'uraian' => 'Pelayanan Kesehatan Pada Usia Lanjut',
                'satuan' => 'Orang',
                'versi' => 2,
            ],
            [
                'layanan_id' => 1,
                'kode' => '8.A.1',
                'uraian' => 'Pelayanan Kesehatan Penderita Hipertensi',
                'satuan' => 'Orang',
                'versi' => 2,
            ],
            [
                'layanan_id' => 1,
                'kode' => '9.A.1',
                'uraian' => 'Pelayanan Kesehatan Penderita Diabetes Melitus',
                'satuan' => 'Orang',
                'versi' => 2,
            ],
            [
                'layanan_id' => 1,
                'kode' => '10.A.1',
                'uraian' => 'Pelayanan Kesehatan Orang Dengan Gangguan Jiwa (ODGJ) Berat',
                'satuan' => 'Orang',
                'versi' => 2,
            ],
            [
                'layanan_id' => 1,
                'kode' => '11.A.1',
                'uraian' => 'Pelayanan Kesehatan Orang Terduga Tuberkulosis',
                'satuan' => 'Orang',
                'versi' => 2,
            ],
            [
                'layanan_id' => 1,
                'kode' => '12.A.1',
                'uraian' => 'Pelayanan Kesehatan Orang Dengan Risiko Terinfeksi Virus Yang Melemahkan Daya Tahan Tubuh Manusia (Human Immunodeficiency Virus)',
                'satuan' => 'Orang',
                'versi' => 2,
            ],
            // Layanan ID 2
            [
                'layanan_id' => 2,
                'kode' => '1.B.1',
                'uraian' => 'Vaksin Tetanus Difteri (Td)',
                'satuan' => 'Vaksin',
                'versi' => '2',
            ],
            [
                'layanan_id' => 2,
                'kode' => '1.B.2',
                'uraian' => 'Tablet tambah darah',
                'satuan' => 'Tablet',
                'catatan' => '180 tablet x jumlah ibu hamil',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '1.B.3',
                'uraian' => 'Alat deteksi resiko Ibu Hamil : Test Kehamilan',
                'satuan' => 'Orang',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '1.B.4',
                'uraian' => 'Alat deteksi resiko Ibu Hamil : Pemeriksaan HB',
                'satuan' => 'Paket',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '1.B.5',
                'uraian' => 'Alat deteksi resiko Ibu Hamil : Pemeriksaan Golongan Darah',
                'satuan' => 'Paket',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '1.B.6',
                'uraian' => 'Alat deteksi resiko Ibu Hamil : Pemeriksaan Glukoprotein Urin',
                'satuan' => 'Paket',
                'catatan' => 'proyeksi pengadaan 15% dari jumlah ibu hamil',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '1.B.7',
                'uraian' => 'Alat deteksi resiko Ibu Hamil : Hepatitis B',
                'satuan' => 'Paket',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '1.B.8',
                'uraian' => 'Alat deteksi resiko Ibu Hamil : Sifilis',
                'satuan' => 'Paket',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '1.B.9',
                'uraian' => 'Alat deteksi resiko Ibu Hamil : HIV',
                'satuan' => 'Paket',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '1.B.10',
                'uraian' => 'Kartu ibu/rekam medis ibu',
                'satuan' => 'Paket',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '1.B.11',
                'uraian' => 'Buku Kesehatan Ibu dan Anak (KIA)',
                'satuan' => 'Buku',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '1.B.12',
                'uraian' => 'Media KIE',
                'satuan' => 'Paket',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '1.B.13',
                'uraian' => 'Gel USG (untuk Puskesmas yang memiliki alat USG)',
                'satuan' => 'Botol',
                'catatan' => 'proyeksi pengadaan 1/15 dari jumlah ibu hamil',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '1.B.14',
                'uraian' => 'Tenaga medis : Dokter/dokter spesialis obstetri dan ginekologi;',
                'satuan' => 'Orang',
                'catatan' => 'angka ideal : dengan rasio 1:2500 penduduk untuk dokter umum dan rasio 1:16000 untuk dokter spesialis kebidanan',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '1.B.15',
                'uraian' => 'Tenaga kesehatan : Perawat',
                'satuan' => 'Orang',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '1.B.16',
                'uraian' => 'Tenaga kesehatan : Bidan',
                'satuan' => 'Orang',
                'catatan' => 'angka ideal : dengan rasio 1:1000 penduduk',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '1.B.17',
                'uraian' => 'Tenaga kesehatan : Tenaga Kefarmasian',
                'satuan' => 'Orang',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '1.B.18',
                'uraian' => 'Tenaga kesehatan : Tenaga Gizi',
                'satuan' => 'Orang',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '1.B.19',
                'uraian' => 'Kunjungan 6 kali ibu hamil selama periode kehamilan (K6)',
                'satuan' => 'Orang',
                'catatan' => 'Satu kali pada trimester pertama, Dua kali pada trimester kedua, Tiga kali pada trimester ketiga',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '2.B.1',
                'uraian' => 'Formulir Partograf',
                'satuan' => 'Formulir',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '2.B.2',
                'uraian' => 'Kartu ibu (rekam medis)',
                'satuan' => 'Paket',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '2.B.3',
                'uraian' => 'Buku Kesehatan Ibu dan Anak (KIA)',
                'satuan' => 'Buku',
                'catatan' => 'Terintegrasi dengan ibu hamil, sesuai kebutuhan bila belum dapat pada masa kehamilan',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '2.B.4',
                'uraian' => 'Media KIE',
                'satuan' => 'Paket',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '2.B.5',
                'uraian' => 'Tenaga medis : Dokter/dokter spesialis obstetri dan ginekologi',
                'satuan' => 'Orang',
                'catatan' => 'angka ideal : dengan rasio 1:2500 penduduk untuk dokter umum dan rasio 1:16000 untuk dokter spesialis kebidanan',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '2.B.6',
                'uraian' => 'Tenaga kesehatan: Bidan',
                'satuan' => 'Paket',
                'catatan' => 'angka ideal : dengan rasio 1:1000 penduduk',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '2.B.7',
                'uraian' => 'Tenaga kesehatan: Perawat',
                'satuan' => 'Orang',
                'catatan' => 'angka ideal : dengan rasio 1:885 penduduk',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '2.B.8',
                'uraian' => 'Tenaga kesehatan : Tenaga Kefarmasian',
                'satuan' => 'Orang',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '2.B.9',
                'uraian' => 'Tenaga kesehatan : Tenaga Gizi',
                'satuan' => 'Orang',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '3.B.1',
                'uraian' => 'Vaksin hepatitis B dosis tunggal (prefilled syringe)',
                'satuan' => 'Vaksin',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '3.B.2',
                'uraian' => 'Vitamin K1 injeksi',
                'satuan' => 'Ampul',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '3.B.3',
                'uraian' => 'Salep/tetes mata antibiotik',
                'satuan' => 'Orang',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '3.B.4',
                'uraian' => 'Formulir bayi baru lahir',
                'satuan' => 'Formulir',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '3.B.5',
                'uraian' => 'Buku Kesehatan Ibu dan Anak (KIA)',
                'satuan' => 'Buku',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '3.B.6',
                'uraian' => 'Media Promosi Komunikasi Informasi dan Edukasi (KIE)',
                'satuan' => 'Paket',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '3.B.7',
                'uraian' => 'Tenaga medis : Dokter/Dokter Spesialis Anak',
                'satuan' => 'Orang',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '3.B.8',
                'uraian' => 'Tenaga kesehatan: Bidan',
                'satuan' => 'Orang',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '3.B.9',
                'uraian' => 'Tenaga kesehatan: Perawat',
                'satuan' => 'Orang',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '3.B.10',
                'uraian' => 'Tenaga kesehatan : Tenaga Kefarmasian',
                'satuan' => 'Orang',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '3.B.11',
                'uraian' => 'Tenaga kesehatan : Tenaga Promosi Kesehatan dan Ilmu Perilaku',
                'satuan' => 'Orang',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '3.B.12',
                'uraian' => 'Tenaga kesehatan : Tenaga Gizi',
                'satuan' => 'Orang',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '3.B.13',
                'uraian' => 'Kader Kesehatan',
                'satuan' => 'Orang',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '4.B.1',
                'uraian' => 'Kuisioner Pra Skrining Perkembangan (KPSP) atau instrumen standar lain yang berlaku',
                'satuan' => 'Dokumen',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '4.B.2',
                'uraian' => 'Formulir Deteksi Dini Tumbuh Kembang Anak (DDTK)',
                'satuan' => 'Formulir',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '4.B.3',
                'uraian' => 'Buku Kartu Ibu dan Anak (KIA)',
                'satuan' => 'Orang',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '4.B.4',
                'uraian' => 'Vitamin A Biru',
                'satuan' => 'Kapsul',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '4.B.5',
                'uraian' => 'Vitamin A Merah',
                'satuan' => 'Kapsul',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '4.B.6',
                'uraian' => 'Vaksin imunisasi dasar: BCG',
                'satuan' => 'Vaksin',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '4.B.7',
                'uraian' => 'Vaksin imunisasi dasar: Polio Tetes',
                'satuan' => 'Vaksin',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '4.B.8',
                'uraian' => 'Vaksin imunisasi dasar: IPV',
                'satuan' => 'Vaksin',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '4.B.9',
                'uraian' => 'Vaksin imunisasi dasar: DPT -HB -Hib',
                'satuan' => 'Vaksin',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '4.B.10',
                'uraian' => 'Vaksin imunisasi dasar: Campak - Rubella',
                'satuan' => 'Vaksin',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '4.B.11',
                'uraian' => 'Vaksin imunisasi lanjutan : DPT -HB -Hib',
                'satuan' => 'Vaksin',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '4.B.12',
                'uraian' => 'Vaksin imunisasi lanjutan : Campak - Rubella',
                'satuan' => 'Vaksin',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '4.B.13',
                'uraian' => 'Jarum suntik dan Bahan Habis Pakai (BHP)',
                'satuan' => 'Unit',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '4.B.14',
                'uraian' => 'Peralatan Anafilaktik',
                'satuan' => 'Paket',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '4.B.15',
                'uraian' => 'Formula Terapi Gizi Buruk',
                'satuan' => 'Paket',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '4.B.16',
                'uraian' => 'Tenaga medis : Dokter',
                'satuan' => 'Unit',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '4.B.17',
                'uraian' => 'Tenaga kesehatan : Bidan',
                'satuan' => 'Orang',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '4.B.18',
                'uraian' => 'Tenaga kesehatan : Perawat',
                'satuan' => 'Orang',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '4.B.19',
                'uraian' => 'Tenaga kesehatan : Tenaga Gizi',
                'satuan' => 'Orang',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '4.B.20',
                'uraian' => 'Guru Paud',
                'satuan' => 'Orang',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '4.B.21',
                'uraian' => 'Kader Kesehatan',
                'satuan' => 'Orang',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '5.B.1',
                'uraian' => 'Form pencatatan/Buku raport kesehatanku',
                'satuan' => 'Buku',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '5.B.2',
                'uraian' => 'Form pencatatan/Buku pemantauan kesehatan',
                'satuan' => 'Buku',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '5.B.3',
                'uraian' => 'Kuesioner skrining kesehatan',
                'satuan' => 'Dokumen',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '5.B.4',
                'uraian' => 'Formulir rekapitulasi hasil pelayanan kesehatan usia sekolah dan remaja di dalam sekolah',
                'satuan' => 'Formulir',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '5.B.5',
                'uraian' => 'Formulir rekapitulasi hasil pelayanan kesehatan usia sekolah dan remaja di luar sekolah',
                'satuan' => 'Formulir',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '5.B.6',
                'uraian' => 'Tablet Tambah Darah pada remaja putri kelas 7-9 dan usia 12-17 tahun diluar sekolah',
                'satuan' => 'Tablet',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '5.B.7',
                'uraian' => 'Alat Pemeriksaan Hb',
                'satuan' => 'Alat',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '5.B.8',
                'uraian' => 'Strip Hb sasaran remaja putri kelas 7',
                'satuan' => 'Strip',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '5.B.9',
                'uraian' => 'Media promosi kesehatan',
                'satuan' => 'Paket',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '5.B.10',
                'uraian' => 'Vaksin Campak Rubela, DT, Td untuk pelaksanaan Bulan Imunisasi Anak Sekolah (BIAS)',
                'satuan' => 'Vaksin',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '5.B.11',
                'uraian' => 'Tenaga medis : Dokter/Dokter gigi',
                'satuan' => 'Orang',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '5.B.12',
                'uraian' => 'Tenaga kesehatan : Bidan',
                'satuan' => 'Orang',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '5.B.13',
                'uraian' => 'Tenaga kesehatan : Perawat',
                'satuan' => 'Orang',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '5.B.14',
                'uraian' => 'Tenaga kesehatan : Tenaga Gizi',
                'satuan' => 'Orang',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '5.B.15',
                'uraian' => 'Tenaga kesehatan : Tenaga Kefarmasian',
                'satuan' => 'Orang',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '5.B.16',
                'uraian' => 'Tenaga kesehatan : Tenaga Kesehatan Masyarakat',
                'satuan' => 'Orang',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '5.B.17',
                'uraian' => 'Tenaga non kesehatan terlatih atau mempunyai kualifikasi tertentu : Guru',
                'satuan' => 'Orang',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '5.B.18',
                'uraian' => 'Tenaga non kesehatan terlatih atau mempunyai kualifikasi tertentu : Kader Kesehatan/dokter kecil/peer conselor',
                'satuan' => 'Orang',
                'versi' => 2,
            ],
            // Data untuk layanan_id 6
            [
                'layanan_id' => 2,
                'kode' => '6.B.1',
                'uraian' => 'Pedoman dan media Komunikasi, Informasi, Edukasi (KIE)',
                'satuan' => 'Paket',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '6.B.2',
                'uraian' => 'Alat : Alat ukur berat badan',
                'satuan' => 'Unit',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '6.B.3',
                'uraian' => 'Alat : Alat ukur tinggi badan',
                'satuan' => 'Unit',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '6.B.4',
                'uraian' => 'Alat : Alat ukur lingkar perut',
                'satuan' => 'Unit',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '6.B.5',
                'uraian' => 'Alat : Tensimeter',
                'satuan' => 'Unit',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '6.B.6',
                'uraian' => 'Alat : Glukometer',
                'satuan' => 'Unit',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '6.B.7',
                'uraian' => 'Alat : Alat Ukur Lingkar Lengan Atas (LILA)',
                'satuan' => 'Unit',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '6.B.8',
                'uraian' => 'Alat : Alat Pemeriksa Hb',
                'satuan' => 'Unit',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '6.B.9',
                'uraian' => 'Reagen pemeriksaan Hb',
                'satuan' => 'Unit',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '6.B.10',
                'uraian' => 'Kit Opthalmologi Komunitas',
                'satuan' => 'Unit',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '6.B.11',
                'uraian' => 'Kuesioner PUMA (Deteksi dini PPOK)',
                'satuan' => 'Dokumen',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '6.B.12',
                'uraian' => 'Alat Pelayanan KB',
                'satuan' => 'Unit',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '6.B.12.a',
                'uraian' => 'Set Pemasangan dan Pencabutan Alat Kontrasepsi Dalam Rahim (AKDR)',
                'satuan' => 'Unit',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '6.B.12.b',
                'uraian' => 'Set Pemasangan dan Pencabutan Implan',
                'satuan' => 'Unit',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '6.B.12.c',
                'uraian' => 'Vasectomi Set',
                'satuan' => 'Unit',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '6.B.13',
                'uraian' => 'Alat : Tes strip gula darah',
                'satuan' => 'Unit',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '6.B.14',
                'uraian' => 'Alat : Lancet',
                'satuan' => 'Unit',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '6.B.15',
                'uraian' => 'Alat : Kapas alkohol',
                'satuan' => 'Unit',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '6.B.16',
                'uraian' => 'Alat : KIT IVA Tes',
                'satuan' => 'Unit',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '6.B.17',
                'uraian' => 'Set Pemasangan dan Pencabutan AKDR',
                'satuan' => 'Unit',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '6.B.18',
                'uraian' => 'Set Pemasangan dan Pencabutan Implan',
                'satuan' => 'Unit',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '6.B.19',
                'uraian' => 'Formulir pencatatan dan pelaporan aplikasi Sistem Informasi Penyakit Tidak Menular (SIPTM)',
                'satuan' => 'Dokumen',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '6.B.20',
                'uraian' => 'Vaksin Tetanus Difteri (td)',
                'satuan' => 'Ampul',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '6.B.21',
                'uraian' => 'Tenaga medis : Dokter',
                'satuan' => 'Orang',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '6.B.22',
                'uraian' => 'Tenaga kesehatan : Bidan',
                'satuan' => 'Orang',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '6.B.23',
                'uraian' => 'Tenaga kesehatan : Perawat',
                'satuan' => 'Orang',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '6.B.24',
                'uraian' => 'Tenaga kesehatan : Tenaga Gizi',
                'satuan' => 'Orang',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '6.B.25',
                'uraian' => 'Tenaga kesehatan : Tenaga Kesehatan Masyarakat',
                'satuan' => 'Orang',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '6.B.26',
                'uraian' => 'Kader kesehatan terlatih dan mempunyai kualifikasi tertentu',
                'satuan' => 'Orang',
                'versi' => 2,
            ],

            [
                'layanan_id' => 2,
                'kode' => '7.B.1',
                'uraian' => 'Alat pemeriksaan deteksi dini: alat ukur berat badan, alat ukur tinggi badan, alat ukur lingkar perut, lingkar lengan atas, dan tensimeter',
                'satuan' => 'Paket',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '7.B.2',
                'uraian' => 'Glukometer (alat pemeriksaan gula darah)',
                'satuan' => 'Paket',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '7.B.3',
                'uraian' => 'Alat pemeriksaan kolesterol',
                'satuan' => 'Paket',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '7.B.4',
                'uraian' => 'Bahan medis Habis Pakai: strip uji pemeriksaan gula darah dan kolesterol, lancet, kapas alkohol',
                'satuan' => 'Paket',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '7.B.5',
                'uraian' => 'Instrumen skrining lansia sederhana (SKILAS), instrumen aktivitas kehidupan sehari-hari (AKS/Activity daily living (ADL Barthel)',
                'satuan' => 'Paket',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '7.B.6',
                'uraian' => 'Buku kesehatan lansia atau aplikasi pencatatan terkait lainnya',
                'satuan' => 'Buku',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '7.B.7',
                'uraian' => 'Media KIE',
                'satuan' => 'Paket',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '7.B.8',
                'uraian' => 'Tenaga medis : Dokter',
                'satuan' => 'Orang',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '7.B.9',
                'uraian' => 'Tenaga kesehatan : Bidan',
                'satuan' => 'Orang',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '7.B.10',
                'uraian' => 'Tenaga kesehatan : Perawat',
                'satuan' => 'Orang',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '7.B.11',
                'uraian' => 'Tenaga kesehatan : Tenaga Gizi',
                'satuan' => 'Orang',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '7.B.12',
                'uraian' => 'Tenaga kesehatan : Tenaga Kesehatan Masyarakat',
                'satuan' => 'Orang',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '7.B.13',
                'uraian' => 'Kader kesehatan terlatih dan mempunyai kualifikasi tertentu',
                'satuan' => 'Orang',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '8.B.1',
                'uraian' => 'Pedoman pengendalian Hipertensi dan media Komunikasi, Informasi, Edukasi (KIE)',
                'satuan' => 'Paket',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '8.B.2',
                'uraian' => 'Obat Hipertensi',
                'satuan' => 'Paket',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '8.B.3',
                'uraian' => 'Tensimeter',
                'satuan' => 'Unit',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '8.B.4',
                'uraian' => 'Formulir pencatatan dan pelaporan Aplikasi Sehat Indonesiaku (ASIK)',
                'satuan' => 'Aplikasi',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '8.B.5',
                'uraian' => 'Media promosi kesehatan',
                'satuan' => 'Paket',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '8.B.6',
                'uraian' => 'Tenaga medis : Dokter',
                'satuan' => 'Orang',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '8.B.7',
                'uraian' => 'Tenaga kesehatan : Bidan',
                'satuan' => 'Orang',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '8.B.8',
                'uraian' => 'Tenaga kesehatan : Perawat',
                'satuan' => 'Orang',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '8.B.9',
                'uraian' => 'Tenaga kesehatan : Tenaga Gizi',
                'satuan' => 'Orang',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '8.B.10',
                'uraian' => 'Tenaga kesehatan : Tenaga promosi kesehatan dan ilmu perilaku',
                'satuan' => 'Orang',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '8.B.11',
                'uraian' => 'Tenaga kesehatan : Tenaga Kefarmasian',
                'satuan' => 'Orang',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '8.B.12',
                'uraian' => 'Tenaga kesehatan : Tenaga Kesehatan Masyarakat',
                'satuan' => 'Orang',
                'versi' => 2,
            ],

            // Data untuk Diabetes Melitus
            [
                'layanan_id' => 2,
                'kode' => '9.B.1',
                'uraian' => 'Obat Diabetes Melitus',
                'satuan' => 'Paket',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '9.B.2',
                'uraian' => 'Fotometer atau Glukometer',
                'satuan' => 'Unit',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '9.B.3',
                'uraian' => 'Reagen Glukosa atau Strip Tes Gula Darah, Kapas Alkohol, Lancet',
                'satuan' => 'Unit',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '9.B.4',
                'uraian' => 'Formulir pencatatan dan pelaporan, aplikasi Sistem Informasi Penyakit Tidak Menular (SIPTM), ASIK, SIMPUS',
                'satuan' => 'Formulir',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '9.B.5',
                'uraian' => 'Pedoman dan media Komunikasi, Informasi, Edukasi (KIE)',
                'satuan' => 'Paket',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '9.B.6',
                'uraian' => 'Sarana dan Prasarana',
                'satuan' => 'Unit',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '9.B.7',
                'uraian' => 'Tenaga medis : Dokter',
                'satuan' => 'Orang',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '9.B.8',
                'uraian' => 'Tenaga kesehatan : Bidan',
                'satuan' => 'Orang',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '9.B.9',
                'uraian' => 'Tenaga kesehatan : Perawat',
                'satuan' => 'Orang',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '9.B.10',
                'uraian' => 'Tenaga kesehatan : Tenaga Kefarmasian',
                'satuan' => 'Orang',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '9.B.11',
                'uraian' => 'Tenaga kesehatan : Tenaga Kesehatan Masyarakat',
                'satuan' => 'Orang',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '9.B.12',
                'uraian' => 'Tenaga kesehatan : Tenaga Gizi',
                'satuan' => 'Orang',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '9.B.13',
                'uraian' => 'Tenaga kesehatan : Teknis Medis (ATLM)',
                'satuan' => 'Orang',
                'versi' => 2,
            ],

            // Data untuk Kesehatan Jiwa
            [
                'layanan_id' => 2,
                'kode' => '10.B.1',
                'uraian' => 'Buku Pedoman Diagnosis Penggolongan dan Diagnosis Gangguan Jiwa (PPDGJ III) atau Buku Pedoman Diagnosis Penggolongan dan Diagnosis Gangguan Jiwa terbaru (bila sudah tersedia)',
                'satuan' => 'Buku',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '10.B.2',
                'uraian' => 'Penyediaan Psikofarmaka',
                'satuan' => 'Jenus',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '10.B.3',
                'uraian' => 'Penyediaan formulir skrining kesehatan jiwa dan/ atau penyediaan melalui aplikasi',
                'satuan' => 'Formulir',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '10.B.4',
                'uraian' => 'Penyediaan formulir pencatatan dan pelaporan melalui sistem informasi kesehatan',
                'satuan' => 'Formulir',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '10.B.5',
                'uraian' => 'Media Komunikasi, Informasi, Edukasi (KIE)',
                'satuan' => 'Media',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '10.B.6',
                'uraian' => 'Tenaga kesehatan : Dokter',
                'satuan' => 'Orang',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '10.B.7',
                'uraian' => 'Tenaga kesehatan : Tenaga kesehatan yang memiliki kompetensi dan kewenangan di bidang kesehatan jiwa',
                'satuan' => 'Orang',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '10.B.8',
                'uraian' => 'Tenaga lain yang terlatih di bidang kesehatan jiwa.',
                'satuan' => 'Orang',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '11.B.1',
                'uraian' => 'Media KIE (Leaflet, Lembar Balik, Poster, Banner)',
                'satuan' => 'Paket',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '11.B.2',
                'uraian' => 'Reagen Zn TB',
                'satuan' => 'Kit',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '11.B.3',
                'uraian' => 'Masker bedah dan Masker N95',
                'satuan' => 'Paket',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '11.B.4',
                'uraian' => 'Pot dahak, Kaca slide, Bahan Habis Pakai (Oil Emersi, Ether Alkohol Lampu Spirtus/Bunsen, Ose/Lidi), Rak pengering',
                'satuan' => 'Paket',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '11.B.5',
                'uraian' => 'Katrid tes cepat molekuler',
                'satuan' => 'Test',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '11.B.6',
                'uraian' => 'Formulir pencatatan dan pelaporan aplikasi Sistem Informasi Penyakit Tidak Menular (SIPTM)',
                'satuan' => 'Dokumen',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '11.B.7',
                'uraian' => 'Pedoman/Standar Operasional Prosedur (SOP)',
                'satuan' => 'Dokumen',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '11.B.8',
                'uraian' => 'Tuberkulin',
                'satuan' => 'Vial',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '11.B.9',
                'uraian' => 'Tenaga medis : Dokter/ dokter spesialis penyakit dalam/ dokter spesialis paru',
                'satuan' => 'Orang',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '11.B.10',
                'uraian' => 'Tenaga kesehatan : Perawat',
                'satuan' => 'Orang',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '11.B.11',
                'uraian' => 'Tenaga kesehatan : Tenaga Kefarmasian',
                'satuan' => 'Orang',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '11.B.12',
                'uraian' => 'Tenaga kesehatan : Tenaga Kesehatan Masyarakat',
                'satuan' => 'Orang',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '11.B.13',
                'uraian' => 'Tenaga kesehatan : Analis Teknik Laboratorium Medik (ATLM)',
                'satuan' => 'Orang',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '11.B.14',
                'uraian' => 'Tenaga kesehatan : Radiografer',
                'satuan' => 'Orang',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '11.B.15',
                'uraian' => 'Kader Kesehatan',
                'satuan' => 'Orang',
                'versi' => 2,
            ],

            // Data untuk HIV
            [
                'layanan_id' => 2,
                'kode' => '12.B.1',
                'uraian' => 'Media KIE (Lembar Balik, Leaflet, Poster, Banner)',
                'satuan' => 'Paket',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '12.B.2',
                'uraian' => 'Tes cepat HIV (RDT) pertama',
                'satuan' => 'Test',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '12.B.3',
                'uraian' => 'Bahan Medis Habis Pakai, Handschoen, Alkohol Swab, Plester, Lancet/Jarum Steril, Jarum Spuit yang sesuai/Vacutainer dan Jarum Sesuai',
                'satuan' => 'Paket',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '12.B.4',
                'uraian' => 'Alat tulis, Rekam medis yang berisi nomor rekam medis, Nomor fasilitas pelayanan kesehatan pelaksana, Nomor KTP/NIK',
                'satuan' => 'Paket',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '12.B.5',
                'uraian' => 'Tenaga medis : Dokter/dokter spesialis penyakit dalam/dokter spesialis kulit dan kelamin',
                'satuan' => 'Orang',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '12.B.6',
                'uraian' => 'Tenaga kesehatan : Bidan',
                'satuan' => 'Orang',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '12.B.7',
                'uraian' => 'Tenaga kesehatan : Perawat',
                'satuan' => 'Orang',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '12.B.8',
                'uraian' => 'Tenaga kesehatan : Ahli Teknologi Laboratorium Medis (ATLM)',
                'satuan' => 'Orang',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '12.B.9',
                'uraian' => 'Tenaga kesehatan : Tenaga Kesehatan Masyarakat',
                'satuan' => 'Orang',
                'versi' => 2,
            ],
            [
                'layanan_id' => 2,
                'kode' => '12.B.10',
                'uraian' => 'Tenaga non kesehatan Terlatih/Mempunyai Kualifikasi tertentu: pendamping dan penjangkauan',
                'satuan' => 'Orang',
                'versi' => 2,
            ],






            // Layanan ID 3
            [
                'layanan_id' => 3,
                'kode' => '1.C.1',
                'uraian' => 'Pelayanan Kesehatan Ibu Hamil',
                'satuan' => 'Rupiah',
                'versi' => 2,
            ],
            [
                'layanan_id' => 3,
                'kode' => '1.C.2',
                'uraian' => 'Pelayanan Kesehatan Ibu Bersalin',
                'satuan' => 'Rupiah',
                'versi' => 2,
            ],
            [
                'layanan_id' => 3,
                'kode' => '1.C.3',
                'uraian' => 'Pelayanan Kesehatan Bayi Baru Lahir',
                'satuan' => 'Rupiah',
                'versi' => 2,
            ],
            [
                'layanan_id' => 3,
                'kode' => '1.C.4',
                'uraian' => 'Pelayanan Kesehatan Balita',
                'satuan' => 'Rupiah',
                'versi' => 2,
            ],
            [
                'layanan_id' => 3,
                'kode' => '1.C.5',
                'uraian' => 'Pelayanan Kesehatan Pada Usia Pendidikan Dasar',
                'satuan' => 'Rupiah',
                'versi' => 2,
            ],
            [
                'layanan_id' => 3,
                'kode' => '1.C.6',
                'uraian' => 'Pelayanan Kesehatan Pada Usia Produktif',
                'satuan' => 'Rupiah',
                'versi' => 2,
            ],
            [
                'layanan_id' => 3,
                'kode' => '1.C.7',
                'uraian' => 'Pelayanan Kesehatan Pada Usia Lanjut',
                'satuan' => 'Rupiah',
                'versi' => 2,
            ],
            [
                'layanan_id' => 3,
                'kode' => '1.C.8',
                'uraian' => 'Pelayanan Kesehatan Penderita Hipertensi',
                'satuan' => 'Rupiah',
                'versi' => 2,
            ],
            [
                'layanan_id' => 3,
                'kode' => '1.C.9',
                'uraian' => 'Pelayanan Kesehatan Penderita Diabetes Melitus',
                'satuan' => 'Rupiah',
                'versi' => 2,
            ],
            [
                'layanan_id' => 3,
                'kode' => '1.C.10',
                'uraian' => 'Pelayanan Kesehatan Orang Dengan Gangguan Jiwa (ODGJ) Berat',
                'satuan' => 'Rupiah',
                'versi' => 2,
            ],
            [
                'layanan_id' => 3,
                'kode' => '1.C.11',
                'uraian' => 'Pelayanan Kesehatan Orang Terduga Tuberkulosis',
                'satuan' => 'Rupiah',
                'versi' => 2,
            ],
            [
                'layanan_id' => 3,
                'kode' => '1.C.12',
                'uraian' => 'Pelayanan Kesehatan Orang Dengan Risiko Terinfeksi Virus Yang Melemahkan Daya Tahan Tubuh Manusia (Human Immunodeficiency Virus)',
                'satuan' => 'Rupiah',
                'versi' => 2,
            ],
        ];

        $dataToInsert = [];
        $dataToInsert2 = [];

        // Loop melalui data dan siapkan array untuk insert
        foreach ($subLayananDataVersiOne as $subLayananOne) {
            $dataToInsert[] = [
                'layanan_id' => $subLayananOne['layanan_id'],
                'kode' => $subLayananOne['kode'],
                'uraian' => $subLayananOne['uraian'],
                'satuan' => $subLayananOne['satuan'],
                'versi' => 1,
                'catatan' => $subLayananOne['catatan'] ?? null,
            ];
            // SubLayanan::create($subLayananOne);
        }

        foreach ($subLayananDataVersiTwo as $subLayananTwo) {
            $dataToInsert[] = [
                'layanan_id' => $subLayananTwo['layanan_id'],
                'kode' => $subLayananTwo['kode'],
                'uraian' => $subLayananTwo['uraian'],
                'satuan' => $subLayananTwo['satuan'],
                'versi' => $subLayananTwo['versi'] ?? 1,
                'catatan' => $subLayananTwo['catatan'] ?? null,
            ];
            // SubLayanan::create($subLayananTwo);
        }


        SubLayanan::insert($dataToInsert);
    }
}
