<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Backend\SPM\SubLayanan;

class SubLayananSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $subLayananDataA = [
            [
                'layanan_id' => 1,
                'kode' => '1.A.1',
                'uraian' => 'Pelayanan Kesehatan Ibu Hamil',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 1,
                'kode' => '2.A.1',
                'uraian' => 'Pelayanan Kesehatan Ibu Bersalin',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 1,
                'kode' => '3.A.1',
                'uraian' => 'Pelayanan Kesehatan Bayi Baru Lahir',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 1,
                'kode' => '4.A.1',
                'uraian' => 'Pelayanan Kesehatan Balita',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 1,
                'kode' => '5.A.1',
                'uraian' => 'Pelayanan Kesehatan Pada Usia Pendidikan Dasar',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 1,
                'kode' => '6.A.1',
                'uraian' => 'Pelayanan Kesehatan Pada Usia Produktif',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 1,
                'kode' => '7.A.1',
                'uraian' => 'Pelayanan Kesehatan Pada Usia Lanjut',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 1,
                'kode' => '8.A.1',
                'uraian' => 'Pelayanan Kesehatan Penderita Hipertensi',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 1,
                'kode' => '9.A.1',
                'uraian' => 'Pelayanan Kesehatan Penderita Diabetes Melitus',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 1,
                'kode' => '10.A.1',
                'uraian' => 'Pelayanan Kesehatan Orang Dengan Gangguan Jiwa (ODGJ) Berat',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 1,
                'kode' => '11.A.1',
                'uraian' => 'Pelayanan Kesehatan Orang Terduga Tuberkulosis',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 1,
                'kode' => '12.A.1',
                'uraian' => 'Pelayanan Kesehatan Orang Dengan Risiko Terinfeksi Virus Yang Melemahkan Daya Tahan Tubuh Manusia (Human Immunodeficiency Virus)',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 2,
                'kode' => '1.B.1',
                'uraian' => 'Vaksin Tetanus Difteri (Td)',
                'satuan' => 'Ampul',
            ],
            [
                'layanan_id' => 2,
                'kode' => '1.B.2',
                'uraian' => 'Tablet tambah darah',
                'satuan' => 'Tablet',
            ],
            [
                'layanan_id' => 2,
                'kode' => '1.B.3',
                'uraian' => 'Alat deteksi resiko Ibu Hamil : Test Kehamilan',
                'satuan' => 'Paket',
            ],
            [
                'layanan_id' => 2,
                'kode' => '1.B.4',
                'uraian' => 'Alat deteksi resiko Ibu Hamil : Pemeriksaan HB',
                'satuan' => 'Paket',
            ],
            [
                'layanan_id' => 2,
                'kode' => '1.B.5',
                'uraian' => 'Alat deteksi resiko Ibu Hamil : Pemeriksaan Golongan Darah',
                'satuan' => 'Paket',
            ],
            [
                'layanan_id' => 2,
                'kode' => '1.B.6',
                'uraian' => 'Alat deteksi resiko Ibu Hamil : Pemeriksaan Glukoprotein Urin',
                'satuan' => 'Paket',
            ],
            [
                'layanan_id' => 2,
                'kode' => '1.B.7',
                'uraian' => '7Kartu ibu/rekam medis ibu',
                'satuan' => 'Paket',
            ],
            [
                'layanan_id' => 2,
                'kode' => '1.B.8',
                'uraian' => 'Buku Kesehatan Ibu dan Anak (KIA)',
                'satuan' => 'Buku',
            ],
            [
                'layanan_id' => 2,
                'kode' => '1.B.9',
                'uraian' => 'Tenaga kesehatan : Dokter/dokter spesialis kebidanan',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 2,
                'kode' => '1.B.10',
                'uraian' => 'Tenaga kesehatan : Bidan',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 2,
                'kode' => '1.B.11',
                'uraian' => 'Tenaga kesehatan : Perawat',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 2,
                'kode' => '1.B.12',
                'uraian' => 'Kunjungan 4 kali ibu hamil selama periode kehamilan (K4) (Satu kali pada trimester pertama, Satu kali pada trimester kedua, Dua kali pada trimester ketiga)',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 2,
                'kode' => '2.B.1',
                'uraian' => 'Formulir Partograf',
                'satuan' => 'Formulir',
            ],
            [
                'layanan_id' => 2,
                'kode' => '2.B.2',
                'uraian' => 'Kartu ibu (rekam medis)',
                'satuan' => 'Paket',
            ],
            [
                'layanan_id' => 2,
                'kode' => '2.B.3',
                'uraian' => 'Buku Kesehatan Ibu dan Anak (KIA)',
                'satuan' => 'Buku',
            ],
            [
                'layanan_id' => 2,
                'kode' => '2.B.4',
                'uraian' => 'Tenaga kesehatan: Dokter/dokter spesialis Kebidanan dan Kandungan',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 2,
                'kode' => '2.B.5',
                'uraian' => 'Tenaga kesehatan: Bidan',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 2,
                'kode' => '2.B.6',
                'uraian' => 'Tenaga kesehatan: Perawat',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 2,
                'kode' => '3.B.1',
                'uraian' => 'Vaksin Hepatitis B0',
                'satuan' => 'Vaksin',
            ],
            [
                'layanan_id' => 2,
                'kode' => '3.B.2',
                'uraian' => 'Vitamin K1 injeksi',
                'satuan' => 'Ampul',
            ],
            [
                'layanan_id' => 2,
                'kode' => '3.B.3',
                'uraian' => 'Salep/tetes mata antibiotik',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 2,
                'kode' => '3.B.4',
                'uraian' => 'Formulir bayi baru lahir',
                'satuan' => 'Formulir',
            ],
            [
                'layanan_id' => 2,
                'kode' => '3.B.5',
                'uraian' => 'Formulir Manajemen Terpadu Bayi Muda (MTBM)',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 2,
                'kode' => '3.B.6',
                'uraian' => 'Buku Kesehatan Ibu dan Anak (KIA)',
                'satuan' => 'Buku',
            ],
            [
                'layanan_id' => 2,
                'kode' => '3.B.7',
                'uraian' => 'Tenaga kesehatan: Dokter/dokter spesialis Anak',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 2,
                'kode' => '3.B.8',
                'uraian' => 'Tenaga kesehatan: Bidan',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 2,
                'kode' => '3.B.9',
                'uraian' => 'Tenaga kesehatan: Perawat',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 2,
                'kode' => '4.B.1',
                'uraian' => 'Kuisioner Pra Skrining Perkembangan (KPSP) atau instrumen standar lain yang berlaku',
                'satuan' => 'Dokumen',
            ],
            [
                'layanan_id' => 2,
                'kode' => '4.B.2',
                'uraian' => 'Formulir Deteksi Dini Tumbuh Kembang Anak (DDTK)',
                'satuan' => 'Formulir',
            ],
            [
                'layanan_id' => 2,
                'kode' => '4.B.3',
                'uraian' => 'Buku Kartu Ibu dan Anak (KIA)',
                'satuan' => 'Buku',
            ],
            [
                'layanan_id' => 2,
                'kode' => '4.B.4',
                'uraian' => 'Vitamin A Biru',
                'satuan' => 'Kapsul',
            ],
            [
                'layanan_id' => 2,
                'kode' => '4.B.5',
                'uraian' => 'Vitamin A Merah',
                'satuan' => 'Kapsul',
            ],
            [
                'layanan_id' => 2,
                'kode' => '4.B.6',
                'uraian' => 'Vaksin imunisasi dasar: HBO',
                'satuan' => 'Vaksin',
            ],
            [
                'layanan_id' => 2,
                'kode' => '4.B.7',
                'uraian' => 'Vaksin imunisasi dasar: BCG',
                'satuan' => 'Vaksin',
            ],
            [
                'layanan_id' => 2,
                'kode' => '4.B.8',
                'uraian' => 'Vaksin imunisasi dasar: Polio',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 2,
                'kode' => '4.B.9',
                'uraian' => 'Vaksin imunisasi dasar: IPV',
                'satuan' => 'Vaksin',
            ],
            [
                'layanan_id' => 2,
                'kode' => '4.B.10',
                'uraian' => 'Vaksin imunisasi dasar: DPT -HB -Hib',
                'satuan' => 'Vaksin',
            ],
            [
                'layanan_id' => 2,
                'kode' => '4.B.11',
                'uraian' => 'Vaksin imunisasi dasar: Campak',
                'satuan' => 'Vaksin',
            ],
            [
                'layanan_id' => 2,
                'kode' => '4.B.12',
                'uraian' => 'Vaksin imunisasi dasar: Rubella',
                'satuan' => 'Vaksin',
            ],
            [
                'layanan_id' => 2,
                'kode' => '4.B.13',
                'uraian' => 'Vaksin imunisasi lanjutan: DPT -HB -Hib',
                'satuan' => 'Vaksin',
            ],
            [
                'layanan_id' => 2,
                'kode' => '4.B.14',
                'uraian' => 'Vaksin imunisasi lanjutan: Campak',
                'satuan' => 'Vaksin',
            ],
            [
                'layanan_id' => 2,
                'kode' => '4.B.15',
                'uraian' => 'Vaksin imunisasi lanjutan: Rubella',
                'satuan' => 'Vaksin',
            ],
            [
                'layanan_id' => 2,
                'kode' => '4.B.16',
                'uraian' => 'Jarum suntik dan Bahan Habis Pakai (BHP)',
                'satuan' => 'Unit',
            ],
            [
                'layanan_id' => 2,
                'kode' => '4.B.17',
                'uraian' => 'Peralatan Anafilaktik',
                'satuan' => 'Paket',
            ],
            [
                'layanan_id' => 2,
                'kode' => '4.B.18',
                'uraian' => 'Tenaga kesehatan : Dokter',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 2,
                'kode' => '4.B.19',
                'uraian' => 'Tenaga kesehatan : Bidan',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 2,
                'kode' => '4.B.20',
                'uraian' => 'Tenaga kesehatan : Perawat',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 2,
                'kode' => '4.B.21',
                'uraian' => 'Tenaga kesehatan : Ahli Gizi',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 2,
                'kode' => '4.B.22',
                'uraian' => 'Tenaga kesehatan : Kader Kesehatan',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 2,
                'kode' => '4.B.23',
                'uraian' => 'Tenaga Non kesehatan : Guru PAUD',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 2,
                'kode' => '5.B.1',
                'uraian' => 'Buku raport kesehatanku',
                'satuan' => 'Buku',
            ],
            [
                'layanan_id' => 2,
                'kode' => '5.B.2',
                'uraian' => 'Buku pemantauan kesehatan',
                'satuan' => 'Buku',
            ],
            [
                'layanan_id' => 2,
                'kode' => '5.B.3',
                'uraian' => 'Kuesioner skrining kesehatan',
                'satuan' => 'Dokumen',
            ],
            [
                'layanan_id' => 2,
                'kode' => '5.B.4',
                'uraian' => 'Formulir rekapitulasi hasil pelayanan kesehatan usia sekolah dan remaja di dalam sekolah',
                'satuan' => 'Dokumen',
            ],
            [
                'layanan_id' => 2,
                'kode' => '5.B.5',
                'uraian' => 'Formulir rekapitulasi hasil pelayanan kesehatan usia sekolah dan remaja di luar sekolah',
                'satuan' => 'Formulir',
            ],
            [
                'layanan_id' => 2,
                'kode' => '5.B.6',
                'uraian' => 'Tenaga kesehatan: Dokter/Dokter gigi',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 2,
                'kode' => '5.B.7',
                'uraian' => 'Tenaga kesehatan: Bidan',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 2,
                'kode' => '5.B.8',
                'uraian' => 'Tenaga kesehatan: Perawat',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 2,
                'kode' => '5.B.9',
                'uraian' => 'Tenaga kesehatan: Ahli Gizi',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 2,
                'kode' => '5.B.10',
                'uraian' => 'Tenaga Kesehatan: Masyarakat',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 2,
                'kode' => '5.B.11',
                'uraian' => 'Tenaga kesehatan: Kader Kesehatan',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 2,
                'kode' => '5.B.12',
                'uraian' => 'Tenaga Non kesehatan: Guru',
                'satuan' => 'Orang',
            ],
            // Data untuk layanan_id 6
            [
                'layanan_id' => 2,
                'kode' => '6.B.1',
                'uraian' => 'Pedoman dan media Komunikasi, Informasi, Edukasi (KIE)',
                'satuan' => 'Pedoman',
            ],
            [
                'layanan_id' => 2,
                'kode' => '6.B.2',
                'uraian' => 'Alat ukur berat badan',
                'satuan' => 'Unit',
            ],
            [
                'layanan_id' => 2,
                'kode' => '6.B.3',
                'uraian' => 'Alat: Alat ukur tinggi badan',
                'satuan' => 'Unit',
            ],
            [
                'layanan_id' => 2,
                'kode' => '6.B.4',
                'uraian' => 'Alat: Alat ukur lingkar perut',
                'satuan' => 'Unit',
            ],
            [
                'layanan_id' => 2,
                'kode' => '6.B.5',
                'uraian' => 'Alat: Tensimeter',
                'satuan' => 'Unit',
            ],
            [
                'layanan_id' => 2,
                'kode' => '6.B.6',
                'uraian' => 'Alat: Glukometer',
                'satuan' => 'Unit',
            ],
            [
                'layanan_id' => 2,
                'kode' => '6.B.7',
                'uraian' => 'Alat: Tes strip gula darah',
                'satuan' => 'Unit',
            ],
            [
                'layanan_id' => 2,
                'kode' => '6.B.8',
                'uraian' => 'Alat: Lancet',
                'satuan' => 'Unit',
            ],
            [
                'layanan_id' => 2,
                'kode' => '6.B.9',
                'uraian' => 'Alat: Kapas alkohol',
                'satuan' => 'Unit',
            ],
            [
                'layanan_id' => 2,
                'kode' => '6.B.10',
                'uraian' => 'Alat: KIT IVA Tes',
                'satuan' => 'Unit',
            ],
            [
                'layanan_id' => 2,
                'kode' => '6.B.11',
                'uraian' => 'Formulir pencatatan dan pelaporan aplikasi Sistem Informasi Penyakit Tidak Menular (SIPTM)',
                'satuan' => 'Dokumen',
            ],
            [
                'layanan_id' => 2,
                'kode' => '6.B.12',
                'uraian' => 'Tenaga kesehatan: Dokter',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 2,
                'kode' => '6.B.13',
                'uraian' => 'Tenaga kesehatan: Bidan',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 2,
                'kode' => '6.B.14',
                'uraian' => 'Tenaga kesehatan: Perawat',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 2,
                'kode' => '6.B.15',
                'uraian' => 'Tenaga kesehatan: Ahli Gizi',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 2,
                'kode' => '6.B.16',
                'uraian' => 'Tenaga Kesehatan Masyarakat',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 2,
                'kode' => '6.B.17',
                'uraian' => 'Tenaga non kesehatan Terlatih/Mempunyai Kualifikasi tertentu',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 2,
                'kode' => '7.B.1',
                'uraian' => 'Strip uji pemeriksaan gula darah, kolesterol',
                'satuan' => 'Paket',
            ],
            [
                'layanan_id' => 2,
                'kode' => '7.B.2',
                'uraian' => 'Instrumen Geriatric Depression Scale (GDS), Intrumen Abbreviated Mental Test (AMT) dan Instrumen Activity Daily Living (ADL) dalam Paket Pengkajian Paripurna Pasien Geriatri (P3G)',
                'satuan' => 'Paket',
            ],
            [
                'layanan_id' => 2,
                'kode' => '7.B.3',
                'uraian' => 'Buku kesehatan lansia',
                'satuan' => 'Buku',
            ],
            [
                'layanan_id' => 2,
                'kode' => '7.B.4',
                'uraian' => 'Tenaga kesehatan: Dokter',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 2,
                'kode' => '7.B.5',
                'uraian' => 'Tenaga kesehatan: Bidan',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 2,
                'kode' => '7.B.6',
                'uraian' => 'Tenaga kesehatan: Perawat',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 2,
                'kode' => '7.B.7',
                'uraian' => 'Tenaga kesehatan: Ahli Gizi',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 2,
                'kode' => '7.B.8',
                'uraian' => 'Tenaga K esehatan Masyarakat',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 2,
                'kode' => '7.B.9',
                'uraian' => 'Tenaga non kesehatan Terlatih/Mempunyai Kualifikasi tertentu',
                'satuan' => 'Orang',
            ],
            // Data untuk layanan_id 8
            [
                'layanan_id' => 2,
                'kode' => '8.B.1',
                'uraian' => 'Pedoman pengendalian Hipertensi dan media Komunikasi, Informasi, Edukasi (KIE)',
                'satuan' => 'Pedoman',
            ],
            [
                'layanan_id' => 2,
                'kode' => '8.B.2',
                'uraian' => 'Tensimeter',
                'satuan' => 'Unit',
            ],
            [
                'layanan_id' => 2,
                'kode' => '8.B.3',
                'uraian' => 'Formulir pencatatan dan pelaporan aplikasi Sistem Informasi Penyakit Tidak Menular (SIPTM)',
                'satuan' => 'Dokumen',
            ],
            [
                'layanan_id' => 2,
                'kode' => '8.B.4',
                'uraian' => 'Tenaga kesehatan: Dokter',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 2,
                'kode' => '8.B.5',
                'uraian' => 'Tenaga kesehatan: Bidan',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 2,
                'kode' => '8.B.6',
                'uraian' => 'Tenaga kesehatan: Perawat',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 2,
                'kode' => '8.B.7',
                'uraian' => 'Tenaga Kesehatan Masyarakat',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 2,
                'kode' => '8.B.8',
                'uraian' => 'Obat Hipertensi',
                'satuan' => 'Paket',
            ],
            // Data untuk layanan_id 9
            [
                'layanan_id' => 2,
                'kode' => '9.B.1',
                'uraian' => 'Alat: Glukometer',
                'satuan' => 'Unit',
            ],
            [
                'layanan_id' => 2,
                'kode' => '9.B.2',
                'uraian' => 'Alat: Strip Tes Gula Darah',
                'satuan' => 'Unit',
            ],
            [
                'layanan_id' => 2,
                'kode' => '9.B.3',
                'uraian' => 'Alat: Kapas Alkohol',
                'satuan' => 'Unit',
            ],
            [
                'layanan_id' => 2,
                'kode' => '9.B.4',
                'uraian' => 'Alat: Lancet',
                'satuan' => 'Unit',
            ],
            [
                'layanan_id' => 2,
                'kode' => '9.B.5',
                'uraian' => 'Formulir pencatatan dan pelaporan aplikasi Sistem Informasi Penyakit Tidak Menular (SIPTM)',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 2,
                'kode' => '9.B.6',
                'uraian' => 'Pedoman dan media Komunikasi, Informasi, Edukasi (KIE)',
                'satuan' => 'Pedoman',
            ],
            [
                'layanan_id' => 2,
                'kode' => '9.B.7',
                'uraian' => 'Tenaga kesehatan: Dokter',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 2,
                'kode' => '9.B.8',
                'uraian' => 'Tenaga kesehatan: Bidan',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 2,
                'kode' => '9.B.9',
                'uraian' => 'Tenaga kesehatan: Perawat',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 2,
                'kode' => ' 9.B.10',
                'uraian' => 'Tenaga kesehatan: Ahli Gizi',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 2,
                'kode' => '9.B.11',
                'uraian' => 'Tenaga Kesehatan Masyarakat',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 2,
                'kode' => '9.B.12',
                'uraian' => 'Obat Diabetes Melitus',
                'satuan' => 'Paket',
            ],
            [
                'layanan_id' => 2,
                'kode' => '10.B.1',
                'uraian' => 'Buku Pedoman Diagnosis Penggolongan Gangguan Jiwa (PPDGJ III) atau Buku Pedoman Diagnosis Penggolongan Gangguan Jiwa terbaru (bila sudah tersedia)',
                'satuan' => 'Buku',
            ],
            [
                'layanan_id' => 2,
                'kode' => '10.B.2',
                'uraian' => 'Kit berisi 2 Alat Fiksasi',
                'satuan' => 'Paket',
            ],
            [
                'layanan_id' => 2,
                'kode' => '10.B.3',
                'uraian' => 'Penyediaan formulir pencatatan dan pelaporan',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 2,
                'kode' => '10.B.4',
                'uraian' => 'Media Komunikasi, Informasi, Edukasi (KIE)',
                'satuan' => 'Media',
            ],
            [
                'layanan_id' => 2,
                'kode' => '10.B.5',
                'uraian' => 'Tenaga kesehatan: Dokter',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 2,
                'kode' => '10.B.6',
                'uraian' => 'Tenaga kesehatan: Perawat Terlatih Jiwa',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 2,
                'kode' => '10.B.7',
                'uraian' => 'Tenaga kesehatan: Tenaga Kesehatan Lainnya',
                'satuan' => 'Orang',
            ],
            // Data untuk layanan_id 11
            [
                'layanan_id' => 2,
                'kode' => '11.B.1',
                'uraian' => 'Media KIE (Leaflet, Lembar Balik, Poster, Banner)',
                'satuan' => 'Media',
            ],
            [
                'layanan_id' => 2,
                'kode' => '11.B.2',
                'uraian' => 'Reagen Zn TB',
                'satuan' => 'Paket',
            ],
            [
                'layanan_id' => 2,
                'kode' => '11.B.3',
                'uraian' => 'Masker jenis rumah tangga dan Masker N95',
                'satuan' => 'Paket',
            ],
            [
                'layanan_id' => 2,
                'kode' => '11.B.4',
                'uraian' => 'Pot dahak, Kaca slide, Bahan Habis Pakai (Oil Emersi, Ether Alkohol Lampu Spirtus/Bunsen, Ose/Lidi), Rak pengering',
                'satuan' => 'Paket',
            ],
            [
                'layanan_id' => 2,
                'kode' => '11.B.5',
                'uraian' => 'Catridge tes cepat molekuler',
                'satuan' => 'Paket',
            ],
            [
                'layanan_id' => 2,
                'kode' => '11.B.6',
                'uraian' => 'Formulir pencatatan dan pelaporan',
                'satuan' => 'Dokumen',
            ],
            [
                'layanan_id' => 2,
                'kode' => '11.B.7',
                'uraian' => 'Pedoman/Standar Operasional Prosedur (SOP)',
                'satuan' => 'Dokumen',
            ],
            [
                'layanan_id' => 2,
                'kode' => '11.B.8',
                'uraian' => 'Dokter/ dokter spesialis penyakit dalam/ dokter spesialis paru',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 2,
                'kode' => '11.B.9',
                'uraian' => 'Tenaga kesehatan: Perawat',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 2,
                'kode' => '11.B.10',
                'uraian' => 'Tenaga kesehatan: Analis Teknik Laboratorium Medik (ATLM)',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 2,
                'kode' => '11.B.11',
                'uraian' => 'Tenaga kesehatan: Penata Rontgen',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 2,
                'kode' => '11.B.12',
                'uraian' => 'Tenaga kesehatan masyarakat',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 2,
                'kode' => '11.B.13',
                'uraian' => 'Tenaga non kesehatan Terlatih/Mempunyai Kualifikasi tertentu',
                'satuan' => 'Orang',
            ],
            // Data untuk layanan_id 12
            [
                'layanan_id' => 2,
                'kode' => '12.B.1',
                'uraian' => 'Media KIE (Lembar Balik, Leaflet, Poster, Banner)',
                'satuan' => 'Media',
            ],
            [
                'layanan_id' => 2,
                'kode' => '12.B.2',
                'uraian' => 'Tes cepat HIV (RDT) pertama',
                'satuan' => 'Paket',
            ],
            [
                'layanan_id' => 2,
                'kode' => '12.B.3',
                'uraian' => 'Bahan Medis Habis Pakai, Handschoen, Alkohol Swab, Plester, Lancet/Jarum Steril, Jarum Spuit yang sesuai/Vacutainer dan Jarum Sesuai',
                'satuan' => 'Paket',
            ],
            [
                'layanan_id' => 2,
                'kode' => '12.B.4',
                'uraian' => 'Alat tulis, Rekam medis yang berisi nomor rekam medis, Nomor fasilitas pelayanan kesehatan pelaksana, Nomor KTP/NIK',
                'satuan' => 'Paket',
            ],
            [
                'layanan_id' => 2,
                'kode' => '12.B.5',
                'uraian' => 'Tenaga kesehatan: Dokter/dokter spesialis penyakit dalam/dokter spesialis kulit dan kelamin',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 2,
                'kode' => '12.B.6',
                'uraian' => 'Tenaga kesehatan: Perawat',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 2,
                'kode' => '12.B.7',
                'uraian' => 'Tenaga kesehatan: Bidan',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 2,
                'kode' => '12.B.8',
                'uraian' => 'Tenaga kesehatan: Ahli Teknologi Laboratorium Medis (ATLM)',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 2,
                'kode' => '12.B.9',
                'uraian' => 'Tenaga kesehatan masyarakat',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 2,
                'kode' => '12.B.10',
                'uraian' => 'Tenaga non kesehatan terlatih atau mempunyai kualifikasi tertentu',
                'satuan' => 'Orang',
            ],
            [
                'layanan_id' => 3,
                'kode' => '1.C.1',
                'uraian' => 'Pelayanan Kesehatan Ibu Hamil',
                'satuan' => 'Rupiah',
            ],
            [
                'layanan_id' => 3,
                'kode' => '1.C.2',
                'uraian' => 'Pelayanan Kesehatan Ibu Bersalin',
                'satuan' => 'Rupiah',
            ],
            [
                'layanan_id' => 3,
                'kode' => '1.C.3',
                'uraian' => 'Pelayanan Kesehatan Bayi Baru Lahir',
                'satuan' => 'Rupiah',
            ],
            [
                'layanan_id' => 3,
                'kode' => '1.C.4',
                'uraian' => 'Pelayanan Kesehatan Balita',
                'satuan' => 'Rupiah',
            ],
            [
                'layanan_id' => 3,
                'kode' => '1.C.5',
                'uraian' => 'Pelayanan Kesehatan Pada Usia Pendidikan Dasar',
                'satuan' => 'Rupiah',
            ],
            [
                'layanan_id' => 3,
                'kode' => '1.C.6',
                'uraian' => 'Pelayanan Kesehatan Pada Usia Produktif',
                'satuan' => 'Rupiah',
            ],
            [
                'layanan_id' => 3,
                'kode' => '1.C.7',
                'uraian' => 'Pelayanan Kesehatan Pada Usia Lanjut',
                'satuan' => 'Rupiah',
            ],
            [
                'layanan_id' => 3,
                'kode' => '1.C.8',
                'uraian' => 'Pelayanan Kesehatan Penderita Hipertensi',
                'satuan' => 'Rupiah',
            ],
            [
                'layanan_id' => 3,
                'kode' => '1.C.9',
                'uraian' => 'Pelayanan Kesehatan Penderita Diabetes Melitus',
                'satuan' => 'Rupiah',
            ],
            [
                'layanan_id' => 3,
                'kode' => '1.C.10',
                'uraian' => 'Pelayanan Kesehatan Orang Dengan Gangguan Jiwa (ODGJ) Berat',
                'satuan' => 'Rupiah',
            ],
            [
                'layanan_id' => 3,
                'kode' => '1.C.11',
                'uraian' => 'Pelayanan Kesehatan Orang Terduga Tuberkulosis',
                'satuan' => 'Rupiah',
            ],
            [
                'layanan_id' => 3,
                'kode' => '1.C.12',
                'uraian' => 'Pelayanan Kesehatan Orang Dengan Risiko Terinfeksi Virus Yang Melemahkan Daya Tahan Tubuh Manusia (Human Immunodeficiency Virus)',
                'satuan' => 'Rupiah',
            ],
        ];

        foreach ($subLayananDataA as $subLayananA) {
            SubLayanan::create($subLayananA);
        }
    }
}
